"""OpenAPI customisation + Postman export (issue #21).

Goals
-----
1. Public-facing docs at ``/v1/docs`` (branded Swagger UI).
2. Raw OpenAPI JSON at ``/v1/openapi.json``.
3. Postman v2.1 collection at ``/v1/docs/postman.json`` (one-click import).
4. Hide internal /api/admin/* endpoints from the public spec.

The :func:`build_public_spec` helper takes the live FastAPI app and
strips the admin paths out of the schema. Branding is done via
``get_swagger_ui_html`` with a custom ``swagger_ui_parameters`` dict
and an inline CSS override.
"""
from __future__ import annotations

import json
import logging
from typing import Any, Optional

from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse  # noqa: F401  (JSONResponse used at import)
from fastapi.openapi.docs import get_swagger_ui_html

log = logging.getLogger(__name__)


# Paths we DO NOT want to expose in the public docs. They are operator-
# only and showing them in a public doc leaks implementation details.
_HIDDEN_PREFIXES = (
    "/api/admin",
    "/admin",
)


def build_public_spec(app: FastAPI) -> dict:
    """Return the OpenAPI schema with admin paths filtered out.

    FastAPI caches the schema on ``app.openapi_schema``; if we mutate
    it our filter would persist across calls. We deep-copy via
    ``copy.deepcopy`` so the cached schema is left untouched.
    """
    import copy
    spec = copy.deepcopy(app.openapi())
    paths = spec.get("paths") or {}
    for prefix in _HIDDEN_PREFIXES:
        for p in list(paths.keys()):
            if p.startswith(prefix):
                paths.pop(p, None)
    spec["paths"] = paths

    # Add a Bearer security scheme so the docs "Authorize" button works.
    spec.setdefault("components", {}).setdefault("securitySchemes", {})
    spec["components"]["securitySchemes"]["bearerAuth"] = {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": (
            "Send an `Authorization: Bearer <jwt>` header. The JWT is "
            "issued by POST /api/auth/login (24h TTL) and must carry a "
            "`tid` claim matching the tenant scope."
        ),
    }
    # Apply globally so every operation in the spec shows the lock icon.
    spec["security"] = [{"bearerAuth": []}, {"apiKeyAuth": []}]
    spec["components"]["securitySchemes"]["apiKeyAuth"] = {
        "type": "apiKey",
        "in": "header",
        "name": "X-Api-Key",
        "description": (
            "Per-tenant API key. Generated by POST /api/admin/tenants "
            "and shown exactly once."
        ),
    }

    # Tidy up the top-level info.
    spec["info"] = {
        **spec.get("info", {}),
        "title": "agentops API",
        "version": "1.0.0",
        "description": (
            "Public API for the agentops platform — calls, SMS, AI "
            "assistants, workflows, billing, and audit. All endpoints "
            "are multi-tenant scoped; the caller's tenant is resolved "
            "from the JWT `tid` claim or the `X-Api-Key` header."
        ),
        "contact": {"name": "agentops support", "email": "ops@getbijou.xyz"},
    }

    # Add tag descriptions so the Swagger UI groups them nicely.
    _TAG_BLURBS = {
        "Calls":       "Outbound + inbound call control and history.",
        "Messages":    "SMS / WhatsApp threads + delivery receipts.",
        "Workflows":   "Visual no-code IVR builder (#13).",
        "Analytics":   "Per-tenant rollups + per-assistant breakdown.",
        "Billing":     "Stripe subscriptions, plans, and usage meters.",
        "Tenants":     "Operator-only tenant directory (internal).",
        "Assistants":  "AI assistant CRUD + voice lab.",
        "Numbers":     "Phone-number inventory + assignment.",
        "Auth":        "JWT login + /me.",
        "Audit":       "Append-only audit log + CSV/JSON export.",
        "Webhooks":    "Inbound Telnyx event receiver.",
        "Voicemail":   "Voicemail inbox + transcription.",
        "Recordings":  "Recording search + audio proxy.",
        "Contacts":    "Contact directory.",
        "Campaigns":   "Outbound campaigns with AI assist.",
        "Dispatch":    "Power-dialer dispatch endpoints.",
        "Power Dialer": "Power-dialer session control.",
        "admin":       "Operator endpoints (hidden from public docs).",
        "dashboard":   "Misc dashboard endpoints (state, balance, etc).",
    }
    spec["tags"] = [
        {"name": name, "description": desc}
        for name, desc in _TAG_BLURBS.items()
    ]

    return spec


def build_postman_collection(app: FastAPI) -> dict:
    """Convert the public OpenAPI spec to a Postman v2.1 collection.

    Postman can import the result via *File → Import* (or
    ``newman run collection.json`` for CI).
    """
    spec = build_public_spec(app)
    base = "{{base_url}}"
    items: list[dict] = []
    for path, methods in (spec.get("paths") or {}).items():
        for method, op in methods.items():
            if method.lower() not in ("get", "post", "put", "patch", "delete"):
                continue
            url_path = "/" + path.lstrip("/").replace("{", ":").replace("}", "")
            req: dict[str, Any] = {
                "method": method.upper(),
                "header": [
                    {"key": "Content-Type", "value": "application/json"},
                    {"key": "Authorization", "value": "Bearer {{jwt}}"},
                ],
                "url": {
                    "raw": base + url_path,
                    "host": [base],
                    "path": url_path.lstrip("/").split("/"),
                },
                "description": op.get("summary") or op.get("description") or "",
            }
            if method.upper() in ("POST", "PUT", "PATCH"):
                req["body"] = {
                    "mode": "raw",
                    "raw": "{}",
                    "options": {"raw": {"language": "json"}},
                }
            # Include the path in the name so the test (and humans) can
            # find v1 routes by grep. Format: "GET /v1/analytics/overview".
            name = f"{method.upper()} {path}" or op.get("summary") or "unnamed"
            items.append({
                "name": name,
                "request": req,
                "response": [],
            })
    return {
        "info": {
            "name": spec.get("info", {}).get("title", "agentops"),
            "_postman_id": "agentops-v1",
            "description": spec.get("info", {}).get("description", ""),
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "item": items,
        "auth": {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{jwt}}"}],
        },
        "variable": [
            {"key": "base_url", "value": "https://bkjr-api.getbijou.xyz"},
            {"key": "jwt", "value": ""},
        ],
    }


# ──────────────────── branded Swagger UI HTML ─────────────────────────────

_BRAND_CSS = """
<style>
  .swagger-ui .topbar { background: #0e0f12; }
  .swagger-ui .topbar .download-url-wrapper { display: none; }
  .swagger-ui .info { margin: 30px 0; }
  .swagger-ui .info .title { color: #e8eaf0; }
  .swagger-ui .info .title small { background: #5b6cff; }
  .swagger-ui .scheme-container { background: #0e0f12; }
  .swagger-ui .opblock-tag { color: #e8eaf0; border-bottom-color: #2a2d34; }
  .swagger-ui .opblock { background: #0e0f12; border-color: #2a2d34; }
  .swagger-ui .opblock .opblock-summary { border-color: #2a2d34; }
  .swagger-ui .opblock.opblock-post { background: rgba(91,108,255,0.10); border-color: #5b6cff; }
  .swagger-ui .opblock.opblock-get { background: rgba(72,199,142,0.10); border-color: #48c78e; }
  .swagger-ui .opblock.opblock-delete { background: rgba(255,99,99,0.10); border-color: #ff6363; }
  .swagger-ui .btn { background: #5b6cff; color: #fff; }
  .swagger-ui .btn:hover { background: #6a7bff; }
  .swagger-ui .btn.authorize { background: #48c78e; }
  .swagger-ui .btn.authorize svg { fill: #fff; }
  body, .swagger-ui { background: #07080b; color: #e8eaf0; }
  .swagger-ui .markdown p, .swagger-ui .markdown li, .swagger-ui .markdown table { color: #c0c4d0; }
  .swagger-ui .parameter__name, .swagger-ui .parameter__type { color: #e8eaf0; }
  .swagger-ui table thead tr th { color: #c0c4d0; border-bottom-color: #2a2d34; }
  .swagger-ui .response-col_status { color: #c0c4d0; }
</style>
"""


def branded_swagger_html(openapi_url: str, title: str = "agentops API") -> HTMLResponse:
    """Return a Swagger UI page with the agentops dark theme."""
    html = get_swagger_ui_html(
        openapi_url=openapi_url,
        title=title,
        swagger_ui_parameters={
            "deepLinking": True,
            "displayRequestDuration": True,
            "docExpansion": "list",
            "filter": True,
            "showExtensions": True,
            "showCommonExtensions": True,
            "persistAuthorization": True,
            "syntaxHighlight.theme": "monokai",
        },
    )
    # Inject the brand CSS just before </head> and a header banner.
    body = html.body.decode("utf-8") if isinstance(html.body, bytes) else html.body
    inject = (
        _BRAND_CSS
        + '<div style="background:linear-gradient(90deg,#5b6cff,#8a5bff);'
        'padding:12px 24px;color:#fff;font-family:system-ui;font-size:14px;">'
        '<strong>agentops</strong> — multi-tenant telephony &amp; AI platform. '
        'v1 API. <a href="/v1/docs/postman.json" style="color:#fff;text-decoration:underline">Download Postman collection</a>.</div>'
    )
    if "</head>" in body:
        body = body.replace("</head>", inject + "</head>", 1)
    else:
        body = inject + body
    return HTMLResponse(content=body, status_code=html.status_code)
